# Generated by Django 5.2.6 on 2025-09-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("DENIED", "Denied"),
                    ("UNDER REVIEW", "Under Review"),
                ],
                max_length=20,
            ),
        ),
    ]
