# Generated by Django 5.2.6 on 2025-09-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_alter_claim_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="insurer_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="claim",
            name="patient_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("DENIED", "Denied"),
                    ("UNDER REVIEW", "Under Review"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
