# Generated by Django 5.2.6 on 2025-09-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_claim_flagged_at_claim_flagged_by_note_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="billed_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The amount originally billed to the insurer.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="flagged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp when the claim was flagged.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who flagged this claim.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flagged_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="insurer_name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the insurance company.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="is_flagged",
            field=models.BooleanField(
                default=False,
                help_text="Mark this claim for special review or follow-up.",
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The amount paid by the insurer.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="patient_name",
            field=models.CharField(
                db_index=True, help_text="Full name of the patient.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("DENIED", "Denied"),
                    ("UNDER REVIEW", "Under Review"),
                ],
                db_index=True,
                help_text="The current processing status of the claim.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="claimdetail",
            name="cpt_codes",
            field=models.CharField(
                help_text="Comma-separated CPT (Current Procedural Terminology) codes.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="claimdetail",
            name="denial_reason",
            field=models.TextField(
                blank=True,
                help_text="The reason provided by the insurer for denying the claim.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="note",
            field=models.TextField(help_text="The content of the note."),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                help_text="The user who created this note.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
